name: mov
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sizer: ^2.0.13
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  http: ^0.13.3
  path_provider: ^2.0.3

flutter:
  uses-material-design: true
assets:
  - package:mov/details_background.jpg
  - package:mov/splash.jpg

